<a href="https://colab.research.google.com/github/SZPiho/L1-and-L2-and-dropout-regularization/blob/main/L1_and_L2_and_dropout_regularization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("https://data.heatonresearch.com/data/t81-558/jh-simple-dataset.csv",na_values=['NA','?'])
df.head(10)

id job area   income     aspect  subscriptions  dist_healthy  save_rate  \
0   1  vv    c  50876.0  13.100000              1      9.017895         35   
1   2  kd    c  60369.0  18.625000              2      7.766643         59   
2   3  pe    c  55126.0  34.766667              1      3.632069          6   
3   4  11    c  51690.0  15.808333              1      5.372942         16   
4   5  kl    d  28347.0  40.941667              3      3.822477         20   
5   6  e2    c  70854.0  40.400000              1     14.893343         87   
6   7  kl    d  38726.0  30.975000              3      3.822477         33   
7   8  nb    a  55162.0  26.966667              2      4.312097         17   
8   9  al    c  67311.0  32.383333              0     25.093772        169   
9  10  pe    a  63344.0  38.233333              1      2.816034          3   

   dist_unhealthy  age  pop_dense  retail_dense     crime product  
0       11.738935   49   0.885827      0.492126  0.071100       b  
1        6.805396   51   0.874016      0.342520  0.400809       c  
2       13.671772   44   0.944882      0.724409  0.207723       b  
3        4.333286   50   0.889764      0.444882  0.361216       b  
4        5.967121   38   0.744094      0.661417  0.068033       a  
5       20.340593   43   0.866142      0.673228  0.473581       d  
6        9.480399   39   0.976378      0.874016  0.092151       f  
7       29.219896   44   1.000000      0.724409  0.162833       b  
8       10.927357   45   0.952756      0.681102  0.096333       c  
9       21.915695   42   0.897638      0.724409  0.173986       c

In [3]:
df=pd.concat([df,pd.get_dummies(df['job'],prefix='job')],axis=1)
df.drop('job',axis=1,inplace=True)

In [4]:
df=pd.concat([df,pd.get_dummies(df['area'],prefix='area')],axis=1)
df.drop('area',axis=1,inplace=True)

In [5]:
med=df['income'].median()
df['income']=df['income'].fillna(med)

In [6]:
df.head(10)

id   income     aspect  subscriptions  dist_healthy  save_rate  \
0   1  50876.0  13.100000              1      9.017895         35   
1   2  60369.0  18.625000              2      7.766643         59   
2   3  55126.0  34.766667              1      3.632069          6   
3   4  51690.0  15.808333              1      5.372942         16   
4   5  28347.0  40.941667              3      3.822477         20   
5   6  70854.0  40.400000              1     14.893343         87   
6   7  38726.0  30.975000              3      3.822477         33   
7   8  55162.0  26.966667              2      4.312097         17   
8   9  67311.0  32.383333              0     25.093772        169   
9  10  63344.0  38.233333              1      2.816034          3   

   dist_unhealthy  age  pop_dense  retail_dense  ...  job_qp job_qw  job_rn  \
0       11.738935   49   0.885827      0.492126  ...       0      0       0   
1        6.805396   51   0.874016      0.342520  ...       0      0       0   
2       13.671772   44   0.944882      0.724409  ...       0      0       0   
3        4.333286   50   0.889764      0.444882  ...       0      0       0   
4        5.967121   38   0.744094      0.661417  ...       0      0       0   
5       20.340593   43   0.866142      0.673228  ...       0      0       0   
6        9.480399   39   0.976378      0.874016  ...       0      0       0   
7       29.219896   44   1.000000      0.724409  ...       0      0       0   
8       10.927357   45   0.952756      0.681102  ...       0      0       0   
9       21.915695   42   0.897638      0.724409  ...       0      0       0   

   job_sa  job_vv  job_zz  area_a  area_b  area_c  area_d  
0       0       1       0       0       0       1       0  
1       0       0       0       0       0       1       0  
2       0       0       0       0       0       1       0  
3       0       0       0       0       0       1       0  
4       0       0       0       0       0       0       1  
5       0       0       0       0       0       1       0  
6       0       0       0       0       0       0       1  
7       0       0       0       1       0       0       0  
8       0       0       0       0       0       1       0  
9       0       0       0       1       0       0       0  

[10 rows x 49 columns]

In [7]:
from scipy.stats import zscore
df['income']=zscore(df['income'])
df['aspect']=zscore(df['aspect'])
df['dist_healthy']=zscore(df['dist_healthy'])
df['save_rate']=zscore(df['save_rate'])
df['dist_unhealthy']=zscore(df['dist_unhealthy'])
df['age']=zscore(df['age'])
df.head(10)

id    income    aspect  subscriptions  dist_healthy  save_rate  \
0   1 -0.607550 -0.664918              1     -0.048411  -0.215764   
1   2  0.338053 -0.207748              2     -0.266765   0.196869   
2   3 -0.184205  1.127906              1     -0.988286  -0.714362   
3   4 -0.526467 -0.440815              1     -0.684488  -0.542432   
4   5 -2.851675  1.638861              3     -0.955058  -0.473660   
5   6  1.382469  1.594040              1      0.976908   0.678274   
6   7 -1.817817  0.814162              3     -0.955058  -0.250150   
7   8 -0.180619  0.482489              2     -0.869615  -0.525239   
8   9  1.029549  0.930695              0      2.756974   2.088104   
9  10  0.634394  1.414758              1     -1.130691  -0.765942   

   dist_unhealthy       age  pop_dense  retail_dense  ...  job_qp job_qw  \
0       -0.314089  0.854321   0.885827      0.492126  ...       0      0   
1       -0.915161  1.394432   0.874016      0.342520  ...       0      0   
2       -0.078604 -0.495957   0.944882      0.724409  ...       0      0   
3       -1.216347  1.124377   0.889764      0.444882  ...       0      0   
4       -1.017291 -2.116291   0.744094      0.661417  ...       0      0   
5        0.733885 -0.766013   0.866142      0.673228  ...       0      0   
6       -0.589255 -1.846235   0.976378      0.874016  ...       0      0   
7        1.815685 -0.495957   1.000000      0.724409  ...       0      0   
8       -0.412966 -0.225902   0.952756      0.681102  ...       0      0   
9        0.925786 -1.036069   0.897638      0.724409  ...       0      0   

   job_rn  job_sa  job_vv  job_zz  area_a  area_b  area_c  area_d  
0       0       0       1       0       0       0       1       0  
1       0       0       0       0       0       0       1       0  
2       0       0       0       0       0       0       1       0  
3       0       0       0       0       0       0       1       0  
4       0       0       0       0       0       0       0       1  
5       0       0       0       0       0       0       1       0  
6       0       0       0       0       0       0       0       1  
7       0       0       0       0       1       0       0       0  
8       0       0       0       0       0       0       1       0  
9       0       0       0       0       1       0       0       0  

[10 rows x 49 columns]

In [8]:
x_col=df.columns.drop('product').drop('id')
x=df[x_col].values
dummies = pd.get_dummies(df['product']) # Classification
products = dummies.columns
y = dummies.values

In [9]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential,regularizers
from tensorflow.keras.layers import Dense,Dropout
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
import numpy as np

In [10]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)
oos_y=[]
oos_pred=[]
fold=0

In [11]:
for train,test in kf.split(x,y):
  fold+=1
  print(f"Fold #{fold}")
        
  x_train = x[train]
  y_train = y[train]
  x_test = x[test]
  y_test = y[test]

  model=Sequential()
  model.add(Dense(128,activation='relu',input_dim=x.shape[1],activity_regularizer=regularizers.l2(1e-4)))
  model.add(Dropout(0.5))
  model.add(Dense(256,activation='relu',activity_regularizer=regularizers.l2(1e-4)))
  model.add(Dropout(0.5))
  model.add(Dense(64,activation='relu',activity_regularizer=regularizers.l2(1e-4)))
  model.add(Dense(y.shape[1],activation='softmax'))
  model.compile(optimizer='adam',loss='categorical_crossentropy')
  model.fit(x_train,y_train,batch_size=100,validation_data=(x_test,y_test),verbose=0,epochs=500)
  pred=model.predict(x_test)
  oos_y.append(y_test)
  pred=np.argmax(pred,axis=1)
  oos_pred.append(pred)
  y_compare=np.argmax(y_test,axis=1)
  score=accuracy_score(y_compare,pred)
  print(f"Fold score (accuracy): {score}")

Fold #1
Fold score (accuracy): 0.6925
Fold #2
Fold score (accuracy): 0.735
Fold #3
Fold score (accuracy): 0.6925
Fold #4
Fold score (accuracy): 0.7375
Fold #5
Fold score (accuracy): 0.6775


In [12]:
oos_y

[array([[0, 1, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0],
        ...,
        [0, 1, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0]], dtype=uint8), array([[0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 1, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0]], dtype=uint8), array([[0, 1, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 1, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0]], dtype=uint8), array([[1, 0, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 1, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 1, ..., 0, 0, 0]], dtype=uint8), array([[0, 0, 1, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
 

In [13]:
oos_y=np.concatenate(oos_y)
oos_y

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [14]:
oos_y.shape

(2000, 7)

In [15]:
oos_pred

[array([2, 1, 2, 3, 1, 2, 1, 1, 1, 2, 2, 0, 2, 1, 1, 1, 2, 0, 2, 1, 2, 1,
        1, 1, 1, 2, 2, 1, 1, 2, 0, 1, 2, 5, 1, 1, 2, 2, 1, 2, 1, 1, 2, 2,
        1, 1, 5, 3, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 0, 1, 1, 2, 2, 1, 2, 1,
        1, 1, 2, 0, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1,
        2, 1, 1, 2, 1, 2, 2, 0, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2,
        1, 1, 0, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 4, 5, 1,
        2, 1, 1, 0, 1, 1, 5, 2, 1, 1, 2, 1, 1, 2, 1, 5, 2, 1, 2, 2, 2, 2,
        1, 1, 1, 1, 2, 2, 1, 1, 0, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 0, 2, 1,
        1, 1, 1, 2, 2, 2, 2, 5, 2, 3, 2, 2, 0, 1, 2, 1, 0, 2, 1, 2, 1, 1,
        2, 0, 2, 1, 1, 1, 1, 1, 1, 2, 3, 2, 1, 1, 0, 5, 1, 3, 2, 1, 2, 2,
        2, 1, 1, 0, 3, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 2, 2,
        1, 2, 2, 5, 1, 1, 1, 2, 0, 2, 2, 1, 1, 0, 2, 2, 2, 1, 2, 1, 2, 1,
        2, 2, 5, 1, 1, 2, 2, 1, 2, 1, 

In [16]:
oos_pred=np.concatenate(oos_pred)

In [17]:
oos_pred

array([2, 1, 2, ..., 2, 1, 0])

In [18]:
oos_pred.shape

(2000,)

In [19]:
oos_y_compare=np.argmax(oos_y,axis=1)

In [20]:
oos_y_compare

array([1, 1, 2, ..., 1, 1, 0])

In [21]:
score = accuracy_score(oos_y_compare, oos_pred)
print(f"Final score (accuracy): {score}")    

Final score (accuracy): 0.707
